// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by FlutterFire CLI. Android values are live (project ptassistant-2f019).
/// iOS is a placeholder — run `flutterfire configure` before shipping an iOS build.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured. Run `flutterfire configure` to add it.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGhLsjc_BTpS_R9KacnFdpdg8A4pRqkjI',
    appId: '1:1068273290837:android:0cc5e1a657164c21228edc',
    messagingSenderId: '1068273290837',
    projectId: 'ptassistant-2f019',
    storageBucket: 'ptassistant-2f019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_REPLACE_VIA_FLUTTERFIRE_CONFIGURE',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'ptassistant-placeholder',
    storageBucket: 'ptassistant-placeholder.appspot.com',
    iosBundleId: 'com.ptassistant.ptassistant',
  );
}
